---
AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM::User"

Parameters:
  Input:
    Type: String
    Default: default

Resources:
  Test:
    Type: "AWS::IAM::User"

Outputs:
  Output:
    Value: !Sub
    - "Ouput from stack '${AWS::StackName}', input param '${Input}'"
    - Input: !Ref Input
